# Generated by Django 4.2.20 on 2025-04-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastUpdate',
            new_name='last_update',
        ),
    ]
